name: secpl.us
favicon: null
layout_spectrum: 0.8459849054925144
typography_spectrum: 0.7060402801726013
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6943540184292942
  lightness: 0.07627126947045326
  saturation: 0.7552195054013282
  rhythmicContrast: 0.1290280232205987
purpose: []
